In [1]:
import pandas as pd
import numpy as np
import torch
import warnings
from src.plot_utils import *
from src.space_model import space_model
from src.nn_model import nnModel
from src.plot_utils import *
from matplotlib import animation
from moviepy.editor import *
warnings.simplefilter(action="ignore", category=DeprecationWarning)

In [2]:
df = pd.read_json('./Data/sample_match_1_w_sog.json')

In [4]:
df

Period   Frame  Time [s]      H11_x     H11_y      H1_x      H1_y  \
0          1       1      0.04    0.08528  32.80184  33.95392  44.41896   
1          1      26      1.04    0.06656  32.72976  33.68144  42.30824   
2          1      51      2.04   -0.02080  32.65768  33.14584  39.65284   
3          1      76      3.04    0.10088  32.68896  33.17912  38.00588   
4          1     101      4.04    0.73632  32.80116  33.81040  39.06464   
...      ...     ...       ...        ...       ...       ...       ...   
5796       2  144901   5796.04  100.73440  28.43352       NaN       NaN   
5797       2  144926   5797.04   99.02360  29.55892       NaN       NaN   
5798       2  144951   5798.04   97.42512  30.57280       NaN       NaN   
5799       2  144976   5799.04   95.72576  31.11816       NaN       NaN   
5800       2  145001   5800.04   94.27496  30.89104       NaN       NaN   

          H2_x      H2_y      H3_x  ...  A13_sq  H4_sq     A5_sq     A9_sq  \
0     35.04904  33.22684  32.16408  ...     NaN    NaN       NaN       NaN   
1     34.59560  32.38772  32.77352  ...     NaN    0.0  0.014185  0.004767   
2     34.02568  31.30992  32.86712  ...     NaN    0.0 -0.001996 -0.016256   
3     34.04856  31.44524  32.99192  ...     NaN    0.0 -0.001419 -0.034305   
4     34.33976  33.44376  33.41936  ...     NaN    0.0  0.024722  0.013183   
...        ...       ...       ...  ...     ...    ...       ...       ...   
5796  37.57832  44.05652  33.76568  ...     NaN    NaN       NaN       NaN   
5797  37.35264  44.18232  32.98672  ...     NaN    NaN       NaN       NaN   
5798  36.87112  44.32784  33.29248  ...     NaN    NaN       NaN       NaN   
5799  36.24400  44.24420  32.88896  ...     NaN    NaN       NaN       NaN   
5800  35.55136  43.92256  32.47920  ...     NaN    NaN       NaN       NaN   

         H9_sq     A4_sq  A14_sq     H1_sq     H2_sq   frame  
0          NaN       NaN     NaN       NaN       NaN       1  
1    -0.017896  0.006917     NaN -0.005273  0.001872      26  
2     0.033800 -0.016325     NaN  0.006292 -0.000238      51  
3     0.004523  0.002440     NaN  0.006415 -0.000232      76  
4     0.012352 -0.015791     NaN  0.009595 -0.004236     101  
...        ...       ...     ...       ...       ...     ...  
5796       NaN       NaN     NaN       NaN       NaN  144901  
5797       NaN       NaN     NaN       NaN       NaN  144926  
5798       NaN       NaN     NaN       NaN       NaN  144951  
5799       NaN       NaN     NaN       NaN       NaN  144976  
5800       NaN       NaN     NaN       NaN       NaN  145001  

[5801 rows x 178 columns]

In [5]:
import re

In [23]:
player_regx = re.compile('[HA][0-9]+_[xy]$')

In [95]:
def space_generation(frame_idx, frame_dif, df):
    previous_frame = frame_idx - frame_dif
    p_list = [i for i in df.columns if re.match(player_regx, i)]
    previous_location = df[df['Frame'] == previous_frame].loc[0, p_list].to_dict()
    return previous_location

In [99]:
aa = space_generation(26, 25, df)

In [100]:
aa

{'H11_x': 0.08528000000000001,
 'H11_y': 32.80184,
 'H1_x': 33.95392,
 'H1_y': 44.41896,
 'H2_x': 35.04904,
 'H2_y': 33.22684,
 'H3_x': 32.16408,
 'H3_y': 24.15972,
 'H4_x': 33.42248,
 'H4_y': 14.45816,
 'H5_x': 42.73776,
 'H5_y': 49.36052,
 'H6_x': 43.36592,
 'H6_y': 32.53324,
 'H7_x': 40.69,
 'H7_y': 22.134,
 'H8_x': 47.20352,
 'H8_y': 14.39832,
 'H9_x': 54.80488,
 'H9_y': 25.8264,
 'H10_x': 57.45272,
 'H10_y': 29.42292,
 'H12_x': nan,
 'H12_y': nan,
 'H13_x': nan,
 'H13_y': nan,
 'H14_x': nan,
 'H14_y': nan,
 'A11_x': 94.12936,
 'A11_y': 32.27416,
 'A1_x': 60.72872,
 'A1_y': 14.13992,
 'A2_x': 70.36432,
 'A2_y': 31.7628,
 'A3_x': 70.0024,
 'A3_y': 52.00368,
 'A4_x': 42.414320000000004,
 'A4_y': 41.837,
 'A5_x': 47.29088,
 'A5_y': 26.32212,
 'A6_x': 58.1984,
 'A6_y': 46.087,
 'A7_x': 57.45272,
 'A7_y': 29.42292,
 'A8_x': 52.06968,
 'A8_y': 64.13896,
 'A9_x': 45.44072,
 'A9_y': 3.40136,
 'A10_x': 39.34632,
 'A10_y': 18.62044,
 'A12_x': nan,
 'A12_y': nan,
 'A13_x': nan,
 'A13_y': nan,

In [37]:
np.matmul(a, a.T)

array([[ 5,  7,  9],
       [ 7, 10, 13],
       [ 9, 13, 17]])

In [41]:
a**2

array([[ 1,  4],
       [ 1,  9],
       [ 1, 16]])

In [52]:
np.tile(np.sum(a**2, axis=1), (3, 1)) - 2 * np.matmul(a, a.T) + np.tile(np.sum(a**2, axis=1).reshape(-1, 1), 3)

array([[0, 1, 4],
       [1, 0, 1],
       [4, 1, 0]])